### ISSUE TITLE
Case sensitivity in Dice rule names

### ISSUE THREAD

**Issue by ethanpooley** [TomBZombie/Dice#29]
I recently made a case error while configuring a Dice rule, with the result that the rule was not applied when I later created the (intended) target object via Dice. My bad. But it made me wonder whether Dice rule names should be handled in a case-insensitive fashion, since they (always?) refer to case-insensitive PHP class names.

There is no way to make Dice intelligently warn about unused rules, or rules that name non-existent classes, so users really just need to avoid mistakes while typing rule names and always consider a rule name error when troubleshooting. But it seems to me that perhaps errors *in case* could easily and consistently be solved by Dice with no ill effects.

**Comment by TomBZombie** [comment]
I've added a fix for this, it slightly impacts performance, 0.1mb more memory usage and about 3% slower in most tests.

**Comment by ethanpooley** [comment]
Ah. So they don't always apply only to PHP classnames, I see. But yeah, depending on case-sensitivity in instance names would be pretty ugly practice. Hopefully no one was doing that—for all sorts of reasons!

Thanks - glad you liked the suggestion.
