### ISSUE TITLE
PHP5.4

### ISSUE THREAD

**Issue by TomBZombie** [TomBZombie/Dice#32]
I've been informed the current 5.4-5.5 branch does not work in PHP5.4 Unfortunately I do not currently have a php5.4 install I can test with.

It looks as if the issue is the foreach ($arr as list()) that was added in #30. 

I'm considering whether it's better to have a 5.4 branch or changing the PHP5.4-5.5 branch so it's compatible with 5.4. From a maintainability point of view keeping a single branch makes life easier.

The 5.4-5.5 branch also needs to have several improvements backported. As PHP5.4 is supported officially until at least september 2015, keeping 5.4 support is important.

**Comment by garrettw** [comment]
I'm emailing you now. My web host has 5.4 and I can set you up with an account to play with since I have a reseller account.

**Comment by TomBZombie** [comment]
I've rebased the PHP5.4-5.5 branch on the 5.6 branch and removed any PHP5.5 and 5.6 features. Rather than having a branch for each it's easier to maintain one.

**Comment by garrettw** [comment]
Ah, very nice. I concur.
