### ISSUE TITLE
Change composer to require php 5.4

### ISSUE THREAD

**Issue by ryanmc2033** [TomBZombie/Dice#33]
You say this version is compatible with 5.4 and up, but in your composer you require 5.6. Can you change this? I am using php 5.5 and composer won't let me install it.

**Comment by ryanmc2033** [comment]
nevermind I see that there is a different branch for php5.5

**Comment by TomBZombie** [comment]
I don't use composer much so I'm happy to change the way composer.json is set up. Both branches are available on packagist and as I understand it, composer will install the version suited to your PHP version.
