### ISSUE TITLE
Header comment formatting on github

### ISSUE THREAD

**Issue by TomBZombie** [TomBZombie/Dice#37]
This has been broken for a while. Not sure why. Both Sublime and Eclipse show the formatting as:

![image](https://cloud.githubusercontent.com/assets/2454540/6185712/9579d676-b369-11e4-8cb7-84beb5c7873a.png)

Yet github shows it with broken formatting.

**Comment by maxwilms** [comment]
Looks like different tab lengths. Sublime uses AFAIK 4 spaces for one tab stop (you can spot it in line 9). Github seems to use 8 spaces. Replace with spaces and it should be fine.

Don't forget to change 2014 to 2015 ;-)

**Comment by TomBZombie** [comment]
Yeah that's it! I've replaced them with spaces.
