### ISSUE TITLE
Notice: Undefined property: Dice\Rule::$instanceof in 

### ISSUE THREAD

**Issue by qooob** [TomBZombie/Dice#40]
Tom, hi! I recently wanted to update `Dice` and have the following warning shown, which weren't  the case before. I know it's me missing something but not sure what?

```
Notice: Undefined property: Dice\Rule::$instanceof in /home/project.development/public_html/plugins/dice/dice.class.php on line 61

Notice: Undefined property: Dice\Rule::$instanceof in /home/project.development/public_html/plugins/dice/dice.class.php on line 77
```

**Comment by TomBZombie** [comment]
Can you tell me which version of Dice you are using? 

Dice only has two places where it references $rule->instanceOf and in both cases it's an uppercase O on instanceOf.

Line 20:

```php
			if ($rule->instanceOf === null && $key !== '*' && is_subclass_of($name, $key) && $rule->inherit === true) return $rule;
```

and  line 29

```php
			$class = new \ReflectionClass($rule->instanceOf ?: $component);
```

FYI I tried to email you back several times last time you emailed me but I always got the error:


```code
This is an automatically generated Delivery Status Notification

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

Delivery to the following recipient has been delayed:

     ilia@rostovtsev.ru

Message will be retried for 2 more day(s)

Technical details of temporary failure:
DNS Error: Timeout while contacting DNS servers

```

**Comment by qooob** [comment]
I just sent a test message. Did you get it?

About this issue, you know, I think we just discovered a phpfmt horrible bug!! It's not `Dice` though!! Sorry for disturbance.

Can you tell me, since when you can use the following syntax in PHP, which is really cool, I think:
```
namespace Dice {
    class Dice {
        private $rules = [];
        private $cache = [];
        private $instances = [];
   }
}
```

**Comment by qooob** [comment]
Tom, did you receive my email?
