### ISSUE TITLE
Issue with constructor params of injected class

### ISSUE THREAD

**Issue by ryanmc2033** [TomBZombie/Dice#50]
I have a class called A that injects another class called B. Class B has a constructor param that is just a plain string, but when that class is created it is being given an object.

```
class A {
    public function __construct(B $b) {
    }
}

class B {
    public function __construct($string = null) {
    }
}
```

How can I get class B created without a param, or with a null param?

I tried putting in a rule like this, but it didn't work.
```
$rule = new \Dice\Rule;
$rule->constructParams = [null];
$dice->addRule('B', $rule);
```

**Comment by TomBZombie** [comment]
This was fixed by daniel-meister in commit 0742ed8fabd9a2aa05a2ce6d6aca2f23524f786b, upgrade to the latest version of Dice (either master for PHP5.6 or the PHP5-4.5.5 branch) and the rule you have will work. 

I have added some test cases to ensure this works as expected.
