### ISSUE TITLE
XML loader classname case doesn't match filename

### ISSUE THREAD

**Issue by garrettw** [TomBZombie/Dice#53]
Loader/Xml.php contains the class "XML". Should the filename be all uppercase, or does it still work fine in all cases?

**Comment by TomBZombie** [comment]
Agreed, these should match. I'll update the class name.

**Comment by TomBZombie** [comment]
n.b. I changed the class name rather than the file name just in case anyone is already loading the file based on the name.

**Comment by garrettw** [comment]
Fine by me. That way it matches the Json class.
