### ISSUE TITLE
Regarding releases...

### ISSUE THREAD

**Issue by garrettw** [TomBZombie/Dice#55]
1. What ever happened to v1.3.1? Did it ever exist?
2. Do you think it's about time to do a new release, with all of the changes that have been made since v1.3.2?

**Comment by daniel-meister** [comment]
A clear release numbering process (e.g. similar to http://semver.org/) would clearly help in using Dice in other projects.

**Comment by TomBZombie** [comment]
Totally agree, I've just changed the version number to 1.4 and created a release. Going forward, I'll try to mark releases/versions more clearly and increment the version in the source code.

Looking forward, PHP7 brings return type hints (Although it doesn't look like there is an `object` hint so I'm not sure how useful it will be) and a few other changes that may be useful. Unless anything unexpected happens between then and now I'll aim for 2.0 being the backwards incompatible PHP7 version.

**Comment by garrettw** [comment]
Sounds good to me! :smile:
