### ISSUE TITLE
Packagist does not know about releases

### ISSUE THREAD

**Issue by m6w6** [TomBZombie/Dice#57]
packagist.org does not know about your releases. I'm not sure what's wrong here, though. Did you setup the packagist service hook for the repository?

**Comment by TomBZombie** [comment]
Thanks for pointing this out. I'm not very knowledgeable about packagist so any advice is welcome. The service hook is set up, and packagist is showing the latest dev- version (Master githhub branch). Is there anything I need to do on packagist to get it to identify releases? I had a look around but there's no obvious option.

**Comment by garrettw** [comment]
This is strange to me. Packagist is supposed to pick up your version tags too, and yours are formatted correctly, so it doesn't seem to add up.

**Comment by garrettw** [comment]
The problem is your `composer.json` -- you need to take out the "version" line.
https://twitter.com/seldaek/status/594575835153223680

**Comment by TomBZombie** [comment]
Aha! Thanks, I'll remove it.

**Comment by garrettw** [comment]
Looks like Packagist still has the same info as before. Maybe try going to the package page and clicking Force Update.

**Comment by TomBZombie** [comment]
It seems to be because when I published the releases those releases had the "Version Line". I've added a new tag now that it's been removed and it's appearing on packagist
