### ISSUE TITLE
Support container-interop?

### ISSUE THREAD

**Issue by GaryJones** [TomBZombie/Dice#59]
Any plans to support https://github.com/container-interop/container-interop ?

**Comment by TomBZombie** [comment]
Haven't really looked at it, but it seems like it would be simple enough:

```php
namespace Dice;
class Interop implements Interop\Container\ContainerInterface {
	private $dice;

	public function __construct(Dice $dice) {
		$this->dice = $dice;
	}

	public function get($id) {
		return $this->dice->create($id);
	}

	public function has($id) {
		//Since Dice can construct any object, this function is irrelevant...
		return true;
	}

}
```

**Comment by garrettw** [comment]
I'm glad to hear someone is working on that kind of thing. I had been wondering if anyone was.

**Comment by TomBZombie** [comment]
What do you think the best way of packaging this is? It's a shame composer doesn't (AFAIK) support optional dependencies. I don't particularly want to give Dice standalone a dependency on this as not everyone will require it so adds unnecessary bloat. Perhaps the answer is a DiceInterop package that has dependencies of Dice and container-interop and just provides the class above.

**Comment by garrettw** [comment]
Composer does let you [suggest dependencies](https://getcomposer.org/doc/04-schema.md#suggest).

**Comment by TomBZombie** [comment]
Aha! Yes, that looks like the most simplistic method. Suggest container-interop and provide the Interop class above.

**Comment by garrettw** [comment]
Instead of `has()` just returning `true`, you might have it at least check if `$id` is a valid class to construct.

**Comment by TomBZombie** [comment]
That's a fair point. There's two options: `class_exists`, which has the problem of not supporting named instances and

```php
try { 
$this->dice->create($id);
return true;
}
catch (\Exception $e) {
return false;
}
```

Which will be a lot slower.

**Comment by garrettw** [comment]
Also note that the interop docs say: "A call to the `get` method with a non-existing id SHOULD throw a `Interop\Container\Exception\NotFoundException`"
... so `get()` should only call `$this->dice->create()` IF a call to `has()` returns `true`.

**Comment by TomBZombie** [comment]
> Only problem is, it would return true if there's a rule for a class that doesn't exist.

I think that's ok, because that would suggest it's a named instance so would still return a valid object if get() was called afterwards.

**Comment by TomBZombie** [comment]
I've just put a basic implementation up here: 

https://github.com/TomBZombie/Dice/blob/v2.0/Interop.php

Looking at how other containers do it e.g. pimple ( https://github.com/moufmouf/pimple-interop ) I'm tempted to make this its own repository.

**Comment by garrettw** [comment]
That's fine. Since my previous comments I have changed my opinion a bit: this whole interop idea doesn't seem to be terribly worthwhile.

**Comment by TomBZombie** [comment]
I've added a separate repo for this. It's better this way anyway because it's not tied to a specific branch of Dice.
