### ISSUE TITLE
$forceNewInstance /newInstances

### ISSUE THREAD

**Issue by TomBZombie** [TomBZombie/Dice#67]
I'm tempted to remove this functionality as it's something I've never needed. Considering it's also possible with named instances it's quite redundant. Removing this lowers the complexity/overhead of Dice.

Is anyone using this feature? In all the comments, bug reports and questions I've had about Dice, none have been about this feature despite the fact that it only works with $shared, which is one of the most common questions I get.

If anyone can provide a real life use-case I'm happy to keep it in, but in the interest of avoiding unnecessary bloat I'd rather remove it.

**Comment by garrettw** [comment]
I don't think I've used it.

**Comment by daniel-meister** [comment]
I've never used/needed this; so +1 to remove it in v2.0.
