### ISSUE TITLE
Nested resolving by interface

### ISSUE THREAD

**Issue by mcgiany** [TomBZombie/Dice#78]
Im trying to use dice for resolve nested interfaces in constructor.
For example:
I have class Customer which has this constructor

```php
public function __construct(IDb $connection)
{
$this->connection->$connection;
}
```

In other file i got DbMySql class that implements IDb interface.

```php
public function __construct(ILogger $logger)
{
$this->logger = $logger;
}
```

And in last file i got EchoLogger class that implements ILogger interface.

Now in index.php i have this:

```php
require_once ("dice/Dice.php");

function __autoload($class)
{
	include_once ($class."class.php");
}

$dice = new \Dice\Dice();

$dice->addRule('DbMySql', ['substitutions' => ['ILogger' => ['instance' => 'EchoLogger']]]);
$dice->addRule('Customer', ['substitutions' => ['IDb' => ['instance' => 'DbMySql']]]);
$instance = $dice->create("Customer");
var_dump($instance);

```

When i run this, i get this output:

Notice: Trying to get property of non-object in /Users/jann/Sites/IoC/Customerclass.php on line 13
object(Customer)#14 (3) { ["name"]=> NULL ["surname"]=> NULL ["connection":"Customer":private]=> NULL } 

When i try just create instance of DbMySql, it works:
just change $instance = $dice->create("Customer"); to $instance = $dice->create("DbMySql");
object(DbMySql)#9 (1) { ["logger":"DbMySql":private]=> object(EchoLogger)#8 (0) { } }

edited by @TomBZombie to improve formatting

**Comment by TomBZombie** [comment]
It looks like a problem in your assignment. This is going to cause your "Trying to get property of non object" error:

```php
	public function __construct(IDb $connection) {
		$this->connection->$connection;
	}
}
```

Shouldn't this be:

```php

	public function __construct(IDb $connection) {
		$this->connection = $connection;
	}
}
```

**Comment by mcgiany** [comment]
Oh ... thx for the quick response. I was probably blind when i didnt see that typoo.
Thx again.
