### ISSUE TITLE
No 1.*, PHP 5.4 version compatible with Composer

### ISSUE THREAD

**Issue by dadasign** [TomBZombie/Dice#79]
Composer is unable to recognise any 1.* version which is compatible with PHP 5.4.
I believe this could be due to version numbers in composer.json being incompatible with branch tags in the following ways:
- tag v1.4 has "version": "1.3.1"
- tag 1.3.2 has "version": "1.3.1"
- tag 1.2.1 has "version": "1.1.2"

When trying to require a 1.* version on PHP 5.4 the output is as follows:
 - tombzombie/dice 1.0.x-dev requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - tombzombie/dice 1.4.1 requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - tombzombie/dice 1.4.1 requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - tombzombie/dice 1.0.x-dev requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - Installation request for tombzombie/dice 1.*@dev -> satisfiable by tombzombie/dice[1.0.x-dev, 1.4.1]

**Comment by aik099** [comment]
But why you're adding `@dev` to the version constrain. This is doing exactly what it's supposed to do: getting dev version, which is PHP 5.6+ only.

**Comment by dadasign** [comment]
Using @dev was just an attempt to get anything including dev versions. Adding @dev to the constrain does not add limitations - it expands the the accepted stability. Regardless - the issue remains the same without dev, with the exception that composer will not consider the v1.0 branch :

    - tombzombie/dice 1.4.1 requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - tombzombie/dice 1.4.1 requires php >=5.6.0 -> your PHP version (5.4.38-1+deb.sury.org~precise+2) or "config.platform.php" value does not satisfy that requirement.
    - Installation request for tombzombie/dice 1.* -> satisfiable by tombzombie/dice[1.4.1].

**Comment by dadasign** [comment]
Thank you for your help. It turns out:
"tombzombie/dice": "dev-v1.0-PHP5.4-5.5"
is the require line I was looking for. I did expect the following to work:
"tombzombie/dice": "1.*"
